### PR TITLE
Removed version constant with console application

### PR DESCRIPTION
**Pull request by michalbundyra**
Provide a narrative description of what you are trying to accomplish:

### CODE REVIEW

**Comment by weierophinney** [comment]
Why? This is something we should be doing when tagging. Having the version helps users easily identify which version they are running, without needing to resort to using composer.

**Comment by michalbundyra** [comment]
@weierophinney we tried to have it in ZendApplicationSkeleton and it doesn't work. Always on release someone forgot to bump this version, and in that package is even easier to ask just for installed package list what will be always accurate.

**Comment by weierophinney** [comment]
@webimpress That's a completely different situation; in that case, we were trying to detail a "framework" or "skeleton" version. In this case, we're detailing the version of the _tool_, which is something we absolutely know.

If you're worried about automation, we can look into webhooks, git hooks, or something like ocramius/package-versions. But this is one place I think having a version makes sense.

**Comment by michalbundyra** [comment]
@weierophinney It's your final decision, I think it's common to ask just for `composer show` results, it gives us more information than just the tool version.

If we are going to keep the version definitely we should have something what will help us to remember about updating that version on release.

**Comment by weierophinney** [comment]
While `composer show` is reasonable for _us_, I've worked with enough users to know that this is not true of everyone.

I looked into ways to resolve this, and the only one I can think of would be if we could install an `update` git hook for the repo... which, with GitHub, just isn't possible.

Another possibility is to use a `pre-commit` hook that calls the current `bin/bump-version` script with the results of `git describe` for the version. The issue with this is that the only time that returns a tag name... is if you have checked out the tag. Additionally, it requires any maintainers to make sure they install the hook in their local checkout.

I'll keep thinking on this. For now, though, I'm rejecting the patch, as this is a feature I'd like us to keep; we just need to figure out a more fool-proof way of ensuring it's updated.

**Comment by geerteltink** [comment]
ocramius/package-versions is built for this.

**Pull request closed without merging**
