### PR TITLE
Extending with tooling cli object

### PR DESCRIPTION
**Pull request by lpj145**
…ommands!

Provide a narrative description of what you are trying to accomplish:

- [ ] Are you fixing a bug?
  - [ ] Detail how the bug is invoked currently.
  - [ ] Detail the original, incorrect behavior.
  - [ ] Detail the new, expected behavior.
  - [ ] Base your feature on the `master` branch, and submit against that branch.
  - [ ] Add a regression test that demonstrates the bug, and proves the fix.
  - [ ] Add a `CHANGELOG.md` entry for the fix.

- [x] Are you creating a new feature?
  - [x] Why is the new feature needed? What purpose does it serve?
  - [ ] How will users use the new feature?
  - [x] Base your feature on the `develop` branch, and submit against that branch.
  - [ ] Add only one feature per pull request; split multiple features over multiple pull requests
  - [ ] Add tests for the new feature.
  - [ ] Add documentation for the new feature.
  - [ ] Add a `CHANGELOG.md` entry for the new feature.

- [ ] Is this related to quality assurance?
  

- [ ] Is this related to documentation?

### CODE REVIEW

**Comment by lpj145** [comment]
Ok, so, if think by the way, we can extend to new dev app based on ToolingApplication, and can add more and customize commands, a only file are checked and verified, but you can inject it by constructor... i think is a best solution... and yours ?

**Comment by lpj145** [comment]
whats cs config your use ?

**Comment by weierophinney** [comment]
@lpj145 Read the `docs/CONTRIBUTING.md` ;-)

The tl;dr: run `composer cs-check` and/or `composer cs-fix`.

**Comment by lpj145** [comment]
what's going wrong ? i dont understand why CI cannot pass it, already run composer cs-fix...

**Comment by lpj145** [comment]
ok... is because doc header 😢 but what your think around this approach ?

**Comment by timothyfisherdev** [comment]
To address the custom commands, what if we pulled all of the commands from the container? This expressive tooling package could provider a ConfigProvider class that registers commands under a top level "commands" key, and feed them into the Application instance like before. It would still allow users to override the built in commands and add new commands if they wish through a ConfigProvider. Then you could decorate and extend as you wish like the rest of zend expressive components.

**Comment by lpj145** [comment]
> To address the custom commands, what if we pulled all of the commands from the container? This expressive tooling package could provider a ConfigProvider class that registers commands under a top level "commands" key, and feed them into the Application instance like before. It would still allow users to override the built in commands and add new commands if they wish through a ConfigProvider. Then you could decorate and extend as you wish like the rest of zend expressive components.

maybe you said for this ? https://github.com/lpj145/expressive-console

**Comment by timothyfisherdev** [comment]
I hadn't seen your package yet, but yes just like that! Would there be any downsides to doing it this way?

**Comment by lpj145** [comment]
yes and not... i think is not course of this package.... i can see intention to one and only package with cli independent.

**Comment by lpj145** [comment]
to solve my issues about this package, decide make package based on this package, and implements my plans.

**Comment by timothyfisherdev** [comment]
I just mean doing something like this in `bin/expressive` **(not tested just an idea):**

```php
#!/usr/bin/env php
<?php
/**
 * Wrapper for all other commands
 *
 * @see       https://github.com/zendframework/zend-expressive-tooling for the canonical source repository
 * @copyright Copyright (c) 2017-2018 Zend Technologies USA Inc. (https://www.zend.com)
 * @license   https://github.com/zendframework/zend-expressive-tooling/blob/master/LICENSE.md New BSD License
 */

declare(strict_types=1);

namespace Zend\Expressive\Tooling;

use PackageVersions\Versions;
use Symfony\Component\Console\Application;

// Setup/verify autoloading
$cwd = getcwd();
if (is_dir($cwd . '/vendor')) {
    echo "Using project autoloader based on current working directory\n";
    chdir($cwd);
    require 'vendor/autoload.php';
} elseif (file_exists($a = __DIR__ . '/../../../autoload.php')) {
    echo "Using project autoloader\n";
    require $a;
} elseif (file_exists($a = __DIR__ . '/../vendor/autoload.php')) {
    echo "Using project autoloader relative to bin directory\n";
    require $a;
} elseif (file_exists($a = __DIR__ . '/../autoload.php')) {
    echo "Using project autoloader relative to vendor directory\n";
    require $a;
} else {
    fwrite(STDERR, 'Cannot locate autoloader; please run "composer install"' . PHP_EOL);
    exit(1);
}

$containerFile = $cwd . '/config/container.php';
$commandList = [];

if (file_exists($containerFile)) {
	$container = require $containerFile;
	$config = $container->has('config') ? $container->get('config') : [];
	$commands = $config['commands'] ?? [];
	$commandList = [];

	foreach ($commands as $command) {
		$commandList[] = $container->get($command);
	}
} else {
	$commandList = [
	    new Factory\CreateFactoryCommand('factory:create'),
	    new CreateMiddleware\CreateMiddlewareCommand('middleware:create'),
	    new MigrateInteropMiddleware\MigrateInteropMiddlewareCommand('migrate:interop-middleware'),
	    new MigrateMiddlewareToRequestHandler\MigrateMiddlewareToRequestHandlerCommand(
	        'migrate:middleware-to-request-handler'
	    ),
	    new Module\CreateCommand('module:create'),
	    new Module\DeregisterCommand('module:deregister'),
	    new Module\RegisterCommand('module:register'),
	];
}

$version = strstr(Versions::getVersion('zendframework/zend-expressive-tooling'), '@', true);

$application = new Application('expressive', $version);
$application->addCommands($commandList);
$application->run();
```

So each command would have it's own factory and this package (zendframework/zend-expressive-tooling) could provide a `ConfigProvider` class with all the factories for the default commands, allowing you to retrieve dependencies from the container and such.

**Comment by timothyfisherdev** [comment]
And if that works you could simplify the `bin/expressive` file and move some of the logic into an Expressive `Application` class:

```php
#!/usr/bin/env php
<?php
/**
 * Wrapper for all other commands
 *
 * @see       https://github.com/zendframework/zend-expressive-tooling for the canonical source repository
 * @copyright Copyright (c) 2017-2018 Zend Technologies USA Inc. (https://www.zend.com)
 * @license   https://github.com/zendframework/zend-expressive-tooling/blob/master/LICENSE.md New BSD License
 */

declare(strict_types=1);

namespace Zend\Expressive\Tooling;

// Setup/verify autoloading
$cwd = getcwd();
if (is_dir($cwd . '/vendor')) {
    echo "Using project autoloader based on current working directory\n";
    chdir($cwd);
    require 'vendor/autoload.php';
} elseif (file_exists($a = __DIR__ . '/../../../autoload.php')) {
    echo "Using project autoloader\n";
    require $a;
} elseif (file_exists($a = __DIR__ . '/../vendor/autoload.php')) {
    echo "Using project autoloader relative to bin directory\n";
    require $a;
} elseif (file_exists($a = __DIR__ . '/../autoload.php')) {
    echo "Using project autoloader relative to vendor directory\n";
    require $a;
} else {
    fwrite(STDERR, 'Cannot locate autoloader; please run "composer install"' . PHP_EOL);
    exit(1);
}

$application = new Application();
$containerFilePath = $cwd . '/config/container.php';

if (file_exists($containerFilePath)) {
	$application->addCommandsFromContainer($containerFilePath);
} else {
	$application->addDefaultCommands();
}

$application->run();
```

```php
<?php

declare(strict_types=1);

namespace Zend\Expressive\Tooling;

use PackageVersions\Versions;
use Psr\Container\ContainerInterface;
use Symfony\Component\Console\Application as SymfonyApplication;

class Application extends SymfonyApplication
{
	public function __construct()
	{
		parent::__construct(
			'expressive',
			strstr(Versions::getVersion('zendframework/zend-expressive-tooling'), '@', true)
		);
	}

	public function addCommandsFromContainer(string $containerFilePath) : void
	{
		$container = (function() use ($containerFilePath) : ContainerInterface {
			return require_once $containerFilePath;
		})();

		$config = $container->has('config') ? $container->get('config') : [];
		$commands = $config['commands'] ?? [];

		foreach ($commands as $command) {
			$this->add($container->get($command));
		}
	}

	public function addDefaultCommands() : void
	{
		$this->addCommands([
		    new Factory\CreateFactoryCommand('factory:create'),
		    new CreateMiddleware\CreateMiddlewareCommand('middleware:create'),
		    new MigrateInteropMiddleware\MigrateInteropMiddlewareCommand('migrate:interop-middleware'),
		    new MigrateMiddlewareToRequestHandler\MigrateMiddlewareToRequestHandlerCommand(
		        'migrate:middleware-to-request-handler'
		    ),
		    new Module\CreateCommand('module:create'),
		    new Module\DeregisterCommand('module:deregister'),
		    new Module\RegisterCommand('module:register'),
		]);
	}
}
```

**Comment by timothyfisherdev** [comment]
**EDIT:** I deleted my earlier comments with code since I realized what @weierophinney was saying in https://github.com/zendframework/zend-expressive-tooling/pull/87 solved the problem I was having. Registering them from a `commands.php` file with an anonymous function would work, wouldn't it?

**Comment by lpj145** [comment]
yep, on my package you can see how implement it.

**Comment by lpj145** [comment]
@weierophinney maybe you can delete composer.lock to solve this issue, and merge ?

**Comment by lpj145** [comment]
Some issues or pr never solved on this package, please feel free to use: https://github.com/lpj145/zend-expressive-tooling :)

**Pull request closed without merging**
